export const typography = {
  fontSize: {
    // small screen typography
    's-display-md': 'var(--typography-s-display-md-font-size)',
    's-heading-lg': 'var(--typography-s-heading-lg-font-size)',
    's-heading-md': 'var(--typography-s-heading-md-font-size)',
    's-heading-sm': 'var(--typography-s-heading-sm-font-size)',
    's-body-lg-medium': 'var(--typography-s-body-lg-medium-font-size)',
    's-body-lg-regular': 'var(--typography-s-body-lg-regular-font-size)',
    's-body-md-bold': 'var(--typography-s-body-md-bold-font-size)',
    's-body-md-medium': 'var(--typography-s-body-md-medium-font-size)',
    's-body-md': 'var(--typography-s-body-md-font-size)',
    's-body-sm-bold': 'var(--typography-s-body-sm-bold-font-size)',
    's-body-sm-medium': 'var(--typography-s-body-sm-medium-font-size)',
    's-body-sm': 'var(--typography-s-body-sm-font-size)',
    's-body-xs-medium': 'var(--typography-s-body-xs-medium-font-size)',
    's-body-xs': 'var(--typography-s-body-xs-font-size)',
    // large screen typography
    'l-display-md': 'var(--typography-l-display-md-font-size)',
    'l-heading-lg': 'var(--typography-l-heading-lg-font-size)',
    'l-heading-md': 'var(--typography-l-heading-md-font-size)',
    'l-heading-sm': 'var(--typography-l-heading-sm-font-size)',
    'l-body-lg-medium': 'var(--typography-l-body-lg-medium-font-size)',
    'l-body-md-bold': 'var(--typography-l-body-md-bold-font-size)',
    'l-body-md-medium': 'var(--typography-l-body-md-medium-font-size)',
    'l-body-md': 'var(--typography-l-body-md-font-size)',
    'l-body-sm-bold': 'var(--typography-l-body-sm-bold-font-size)',
    'l-body-sm-medium': 'var(--typography-l-body-sm-medium-font-size)',
    'l-body-sm': 'var(--typography-l-body-sm-font-size)',
    'l-body-xs-medium': 'var(--typography-l-body-xs-medium-font-size)',
    'l-body-xs': 'var(--typography-l-body-xs-font-size)',
  },
  fontFamily: {
    sans: [
      'Euclid Circular B', // This should match @font-face set in tailwind.css
      'Helvetica Neue',
      'Helvetica',
      'Arial',
      'sans-serif',
    ],
    // small screen typography
    's-display-md': 'var(--typography-s-display-md-font-family)',
    's-heading-lg': 'var(--typography-s-heading-lg-font-family)',
    's-heading-md': 'var(--typography-s-heading-md-font-family)',
    's-heading-sm': 'var(--typography-s-heading-sm-font-family)',
    's-body-lg-medium': 'var(--typography-s-body-lg-medium-font-family)',
    's-body-lg-regular': 'var(--typography-s-body-lg-regular-font-family)',
    's-body-md-bold': 'var(--typography-s-body-md-bold-font-family)',
    's-body-md-medium': 'var(--typography-s-body-md-medium-font-family)',
    's-body-md': 'var(--typography-s-body-md-font-family)',
    's-body-sm-bold': 'var(--typography-s-body-sm-bold-font-family)',
    's-body-sm-medium': 'var(--typography-s-body-sm-medium-font-family)',
    's-body-sm': 'var(--typography-s-body-sm-font-family)',
    's-body-xs-medium': 'var(--typography-s-body-xs-medium-font-family)',
    's-body-xs': 'var(--typography-s-body-xs-font-family)',
    // large screen typography
    'l-display-md': 'var(--typography-l-display-md-font-family)',
    'l-heading-lg': 'var(--typography-l-heading-lg-font-family)',
    'l-heading-md': 'var(--typography-l-heading-md-font-family)',
    'l-heading-sm': 'var(--typography-l-heading-sm-font-family)',
    'l-body-lg-medium': 'var(--typography-l-body-lg-medium-font-family)',
    'l-body-md-bold': 'var(--typography-l-body-md-bold-font-family)',
    'l-body-md-medium': 'var(--typography-l-body-md-medium-font-family)',
    'l-body-md': 'var(--typography-l-body-md-font-family)',
    'l-body-sm-bold': 'var(--typography-l-body-sm-bold-font-family)',
    'l-body-sm-medium': 'var(--typography-l-body-sm-medium-font-family)',
    'l-body-sm': 'var(--typography-l-body-sm-font-family)',
    'l-body-xs-medium': 'var(--typography-l-body-xs-medium-font-family)',
    'l-body-xs': 'var(--typography-l-body-xs-font-family)',
  },
  letterSpacing: {
    // small screen typography
    's-display-md': 'var(--typography-s-display-md-letter-spacing)',
    's-heading-lg': 'var(--typography-s-heading-lg-letter-spacing)',
    's-heading-md': 'var(--typography-s-heading-md-letter-spacing)',
    's-heading-sm': 'var(--typography-s-heading-sm-letter-spacing)',
    's-body-lg-medium': 'var(--typography-s-body-lg-medium-letter-spacing)',
    's-body-lg-regular': 'var(--typography-s-body-lg-regular-letter-spacing)',
    's-body-md-bold': 'var(--typography-s-body-md-bold-letter-spacing)',
    's-body-md-medium': 'var(--typography-s-body-md-medium-letter-spacing)',
    's-body-md': 'var(--typography-s-body-md-letter-spacing)',
    's-body-sm-bold': 'var(--typography-s-body-sm-bold-letter-spacing)',
    's-body-sm-medium': 'var(--typography-s-body-sm-medium-letter-spacing)',
    's-body-sm': 'var(--typography-s-body-sm-letter-spacing)',
    's-body-xs-medium': 'var(--typography-s-body-xs-medium-letter-spacing)',
    's-body-xs': 'var(--typography-s-body-xs-letter-spacing)',
    // large screen typography
    'l-display-md': 'var(--typography-l-display-md-letter-spacing)',
    'l-heading-lg': 'var(--typography-l-heading-lg-letter-spacing)',
    'l-heading-md': 'var(--typography-l-heading-md-letter-spacing)',
    'l-heading-sm': 'var(--typography-l-heading-sm-letter-spacing)',
    'l-body-lg-medium': 'var(--typography-l-body-lg-medium-letter-spacing)',
    'l-body-md-bold': 'var(--typography-l-body-md-bold-letter-spacing)',
    'l-body-md-medium': 'var(--typography-l-body-md-medium-letter-spacing)',
    'l-body-md': 'var(--typography-l-body-md-letter-spacing)',
    'l-body-sm-bold': 'var(--typography-l-body-sm-bold-letter-spacing)',
    'l-body-sm-medium': 'var(--typography-l-body-sm-medium-letter-spacing)',
    'l-body-sm': 'var(--typography-l-body-sm-letter-spacing)',
    'l-body-xs-medium': 'var(--typography-l-body-xs-medium-letter-spacing)',
    'l-body-xs': 'var(--typography-l-body-xs-letter-spacing)',
  },
  fontWeight: {
    // small screen typography
    's-display-md': 'var(--typography-s-display-md-font-weight)',
    's-heading-lg': 'var(--typography-s-heading-lg-font-weight)',
    's-heading-md': 'var(--typography-s-heading-md-font-weight)',
    's-heading-sm': 'var(--typography-s-heading-sm-font-weight)',
    's-body-lg-medium': 'var(--typography-s-body-lg-medium-font-weight)',
    's-body-lg-regular': 'var(--typography-s-body-lg-regular-font-weight)',
    's-body-md-bold': 'var(--typography-s-body-md-bold-font-weight)',
    's-body-md-medium': 'var(--typography-s-body-md-medium-font-weight)',
    's-body-md': 'var(--typography-s-body-md-font-weight)',
    's-body-sm-bold': 'var(--typography-s-body-sm-bold-font-weight)',
    's-body-sm-medium': 'var(--typography-s-body-sm-medium-font-weight)',
    's-body-sm': 'var(--typography-s-body-sm-font-weight)',
    's-body-xs-medium': 'var(--typography-s-body-xs-medium-font-weight)',
    's-body-xs': 'var(--typography-s-body-xs-font-weight)',
    // large screen typography
    'l-display-md': 'var(--typography-l-display-md-font-weight)',
    'l-heading-lg': 'var(--typography-l-heading-lg-font-weight)',
    'l-heading-md': 'var(--typography-l-heading-md-font-weight)',
    'l-heading-sm': 'var(--typography-l-heading-sm-font-weight)',
    'l-body-lg-medium': 'var(--typography-l-body-lg-medium-font-weight)',
    'l-body-md-bold': 'var(--typography-l-body-md-bold-font-weight)',
    'l-body-md-medium': 'var(--typography-l-body-md-medium-font-weight)',
    'l-body-md': 'var(--typography-l-body-md-font-weight)',
    'l-body-sm-bold': 'var(--typography-l-body-sm-bold-font-weight)',
    'l-body-sm-medium': 'var(--typography-l-body-sm-medium-font-weight)',
    'l-body-sm': 'var(--typography-l-body-sm-font-weight)',
    'l-body-xs-medium': 'var(--typography-l-body-xs-medium-font-weight)',
    'l-body-xs': 'var(--typography-l-body-xs-font-weight)',
  },
  lineHeight: {
    // small screen typography
    's-display-md': 'var(--typography-s-display-md-line-height)',
    's-heading-lg': 'var(--typography-s-heading-lg-line-height)',
    's-heading-md': 'var(--typography-s-heading-md-line-height)',
    's-heading-sm': 'var(--typography-s-heading-sm-line-height)',
    's-body-lg-medium': 'var(--typography-s-body-lg-medium-line-height)',
    's-body-lg-regular': 'var(--typography-s-body-lg-regular-line-height)',
    's-body-md-bold': 'var(--typography-s-body-md-bold-line-height)',
    's-body-md-medium': 'var(--typography-s-body-md-medium-line-height)',
    's-body-md': 'var(--typography-s-body-md-line-height)',
    's-body-sm-bold': 'var(--typography-s-body-sm-bold-line-height)',
    's-body-sm-medium': 'var(--typography-s-body-sm-medium-line-height)',
    's-body-sm': 'var(--typography-s-body-sm-line-height)',
    's-body-xs-medium': 'var(--typography-s-body-xs-medium-line-height)',
    's-body-xs': 'var(--typography-s-body-xs-line-height)',
    // large screen typography
    'l-display-md': 'var(--typography-l-display-md-line-height)',
    'l-heading-lg': 'var(--typography-l-heading-lg-line-height)',
    'l-heading-md': 'var(--typography-l-heading-md-line-height)',
    'l-heading-sm': 'var(--typography-l-heading-sm-line-height)',
    'l-body-lg-medium': 'var(--typography-l-body-lg-medium-line-height)',
    'l-body-md-bold': 'var(--typography-l-body-md-bold-line-height)',
    'l-body-md-medium': 'var(--typography-l-body-md-medium-line-height)',
    'l-body-md': 'var(--typography-l-body-md-line-height)',
    'l-body-sm-bold': 'var(--typography-l-body-sm-bold-line-height)',
    'l-body-sm-medium': 'var(--typography-l-body-sm-medium-line-height)',
    'l-body-sm': 'var(--typography-l-body-sm-line-height)',
    'l-body-xs-medium': 'var(--typography-l-body-xs-medium-line-height)',
    'l-body-xs': 'var(--typography-l-body-xs-line-height)',
  },
};
